from __future__ import annotations

import email.utils
import textwrap
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from app.config import settings
from app.source_config import SourceDefinition, page_title

# NomadNet's Micron parser treats any line starting with "-" as a horizontal
# divider and discards the rest of the line, so list items must never start
# with a bare hyphen. Use this bullet marker for all list content instead.
_BULLET = "*"


class NomadNetRenderer:
    """Renders normalized feed payloads into lightweight NomadNet-friendly text."""

    def __init__(self, output_dir: Path | None = None) -> None:
        self.output_dir = output_dir or settings.nomadnet_dir

    def render_space_weather(self, payload: dict[str, Any], summary: str) -> str:
        normalized = payload.get("normalized", {}) if isinstance(payload, dict) else {}
        lines = [
            self._heading("Space Weather Brief"),
            self._divider(),
            f"Updated: {self._human_time(normalized.get('updated', payload.get('fetched_at', 'unknown')))}",
            f"SFI: {normalized.get('sfi', 0)}",
            f"Planetary K-Index: {normalized.get('k_index', 0)}",
            f"Geomagnetic Storm Risk: {normalized.get('geomagnetic_storm', 'UNKNOWN')}",
            "",
            "Summary:",
            summary,
            "",
            "Source: NOAA SWPC",
        ]
        return self._normalize(lines)

    def render_cyber_kev(self, payload: dict[str, Any], summary: str) -> str:
        rows = payload.get("latest_five", []) if isinstance(payload, dict) else []
        lines = [
            self._heading("Cyber Threat Brief"),
            self._divider(),
            f"Catalog Size: {payload.get('count_total', 0)}",
            f"Updated: {self._human_time(payload.get('fetched_at', 'unknown'))}",
            "",
            "Latest Known Exploited Vulnerabilities:",
        ]
        if not rows:
            lines.append(f"{_BULLET} No recent KEV entries available.")
        for entry in rows[:5]:
            lines.append(
                f"{_BULLET} {self._escape(entry.get('cveID', 'n/a'))} | {self._escape(entry.get('vendorProject', 'n/a'))} | "
                f"{self._escape(entry.get('vulnerabilityName', 'n/a'))} ({entry.get('dateAdded', 'n/a')})"
            )

        lines.extend(["", "Summary:", self._escape(summary), "", "Source: CISA KEV"])
        return self._normalize(lines)

    def render_news(self, payload: dict[str, Any], summary: str) -> str:
        items = payload.get("items", []) if isinstance(payload, dict) else []
        lines = [
            self._heading("News Brief"),
            self._divider(),
            f"Updated: {self._human_time(payload.get('fetched_at', 'unknown'))}",
            f"Feed Count: {payload.get('source_count', 0)}",
            "",
            "Top Headlines:",
        ]
        if not items:
            lines.append(f"{_BULLET} No news items available.")
        for item in items[:10]:
            lines.extend(self._render_headline(item))

        lines.extend(["", "Summary:", self._escape(summary)])
        return self._normalize(lines)

    def render_weather(self, payload: dict[str, Any], summary: str) -> str:
        items = payload.get("items", []) if isinstance(payload, dict) else []
        weather_items = [
            item
            for item in items
            if any(
                keyword in f"{item.get('title', '')} {item.get('body', '')}".lower()
                for keyword in ("weather", "storm", "alert", "flood", "hurricane", "tornado")
            )
        ]
        lines = [
            self._heading("Weather Alert Brief"),
            self._divider(),
            f"Updated: {self._human_time(payload.get('fetched_at', 'unknown'))}",
            "",
            "Recent Weather/Alert Headlines:",
        ]
        if not weather_items:
            lines.append(f"{_BULLET} No weather-related alerts detected in configured feeds.")
        for item in weather_items[:10]:
            lines.extend(self._render_headline(item))
        lines.extend(["", "Summary:", self._escape(summary)])
        return self._normalize(lines)

    def render_index(self, pages: list[tuple[str, str]] | None = None) -> str:
        links = pages or [
            ("weather.mu", "Weather Alerts Brief"),
            ("space.mu", "Space Weather Brief"),
            ("cyber.mu", "Cyber Threat Brief"),
            ("news.mu", "News Brief"),
            (settings.system_health_page_name, "System Telemetry"),
        ]
        lines = [
            self._heading("Phantom Aggregator"),
            self._divider(),
            "",
        ]
        for page_name, title in links:
            lines.append(f"`_`[{title}`{self._local_page_url(page_name)}]`_`")
        lines.extend(["", "Generated by phantom-aggregator"])
        return self._normalize(lines)

    def write_page(self, page_name: str, content: str) -> Path:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / page_name
        path.write_text(content, encoding="utf-8")
        return path

    def write_index(self) -> Path:
        return self.write_page("index.mu", self.render_index())

    def write_dynamic_index(self, sources: list[SourceDefinition]) -> Path:
        pages: list[tuple[str, str]] = []
        seen: set[str] = set()
        grouped: dict[str, list[SourceDefinition]] = {}
        for source in sources:
            grouped.setdefault(source.nomadnet_page, []).append(source)
        for page_name in sorted(grouped):
            if page_name in seen:
                continue
            seen.add(page_name)
            pages.append((page_name, page_title(page_name, grouped[page_name])))
        pages.append((settings.system_health_page_name, "System Telemetry"))
        return self.write_page("index.mu", self.render_index(pages))

    def render_system_health(self, payload: dict[str, Any]) -> str:
        system = payload.get("system", {}) if isinstance(payload, dict) else {}
        cpu = system.get("cpu", {}) if isinstance(system, dict) else {}
        memory = system.get("memory", {}) if isinstance(system, dict) else {}
        storage = system.get("storage", {}) if isinstance(system, dict) else {}
        connectivity = system.get("connectivity", {}) if isinstance(system, dict) else {}
        internet = connectivity.get("internet", {}) if isinstance(connectivity, dict) else {}
        mesh = connectivity.get("mesh", {}) if isinstance(connectivity, dict) else {}
        lines = [
            self._heading("System Telemetry"),
            self._divider(),
            f"Updated: {self._human_time(payload.get('fetched_at', 'unknown'))}",
            f"CPU: {cpu.get('usage_percent', 0)}% used, {cpu.get('temperature_c', 'unavailable')} C",
            f"RAM: {memory.get('used_percent', 0)}% used, {memory.get('available_mb', 0)} MB free",
            f"Storage ({storage.get('path', '/app/data')}): {storage.get('used_percent', 0)}% used, "
            f"{storage.get('free_gb', 0)} GB free",
            f"Internet: {'reachable' if internet.get('reachable', False) else 'unreachable'}",
            f"Mesh: {'connected' if mesh.get('connected', False) else 'disconnected'}",
        ]
        mesh_interfaces = mesh.get("interfaces", []) if isinstance(mesh, dict) else []
        if mesh_interfaces:
            lines.append("Mesh Interfaces:")
            for interface in mesh_interfaces[:5]:
                status = "up" if interface.get("is_up", False) else "down"
                addr = "addressed" if interface.get("has_address", False) else "no address"
                lines.append(f"{_BULLET} {interface.get('name', 'unknown')}: {status}, {addr}")
        lines.extend(["", "Generated by phantom-aggregator"])
        return self._normalize(lines)

    def render_dynamic_page(
        self,
        page_name: str,
        source_snapshots: list[tuple[SourceDefinition, dict[str, Any] | None]],
    ) -> str:
        if self._is_emergency_page(page_name):
            return self._render_emergency_page(page_name, source_snapshots)
        defined_sources = [source for source, _ in source_snapshots]
        lines = [
            self._heading(page_title(page_name, defined_sources)),
            self._divider(),
            "",
        ]
        if not source_snapshots:
            lines.extend(["No configured sources for this page.", "", "Generated by phantom-aggregator"])
            return self._normalize(lines)

        for index, (source, snapshot) in enumerate(source_snapshots):
            lines.extend(self._render_source_section(source, snapshot))
            if index < len(source_snapshots) - 1:
                lines.extend(["", self._divider(), ""])
        return self._normalize(lines)

    def _render_source_section(self, source: SourceDefinition, snapshot: dict[str, Any] | None) -> list[str]:
        lines = [
            self._subheading(self._escape(source.name)),
            f"{source.category.title()} feed \u00b7 {self._domain(source.url)}",
        ]
        if not snapshot:
            lines.append("Status: awaiting first successful fetch")
            return lines

        payload = snapshot.get("payload", {}) if isinstance(snapshot, dict) else {}
        summary = snapshot.get("summary", "No summary available.") if isinstance(snapshot, dict) else "No summary available."
        lines.append(f"Updated: {self._human_time(snapshot.get('fetched_at', payload.get('fetched_at', 'unknown')))}")

        parser = source.options.get("parser")
        if parser == "space_weather_swpc":
            normalized = payload.get("normalized", {}) if isinstance(payload, dict) else {}
            lines.extend(
                [
                    f"SFI: {normalized.get('sfi', 0)}",
                    f"Planetary K-Index: {normalized.get('k_index', 0)}",
                    f"Geomagnetic Storm Risk: {normalized.get('geomagnetic_storm', 'UNKNOWN')}",
                ]
            )
        elif parser == "cisa_kev":
            lines.append(f"Catalog Size: {payload.get('count_total', 0)}")
            lines.append("Latest Entries:")
            for entry in payload.get("latest_five", [])[:5]:
                lines.append(
                    f"{_BULLET} {self._escape(entry.get('cveID', 'n/a'))} | {self._escape(entry.get('vendorProject', 'n/a'))} | "
                    f"{self._escape(entry.get('vulnerabilityName', 'n/a'))} ({entry.get('dateAdded', 'n/a')})"
                )
        elif source.type in {"rss", "atom"}:
            items = payload.get("items", []) if isinstance(payload, dict) else []
            lines.append(f"Items Available: {len(items)}")
            lines.append("Headlines:")
            for item in items[:5]:
                lines.extend(self._render_headline(item))
        elif source.type == "text_feed":
            lines.append(f"Line Count: {payload.get('line_count', 0)}")
            lines.append("Preview:")
            for line in payload.get("lines", [])[:5]:
                lines.append(f"{_BULLET} {self._escape(line)}")
        else:
            preview = payload.get("preview", {}) if isinstance(payload, dict) else {}
            lines.append("Preview:")
            if isinstance(preview, dict):
                for key, value in list(preview.items())[:5]:
                    lines.append(f"{_BULLET} {self._escape(key)}: {self._escape(value)}")
            else:
                lines.append(f"{_BULLET} {self._escape(preview)}")

        lines.extend(["", "Summary:", self._escape(summary)])
        return lines

    def _render_headline(self, item: dict[str, Any]) -> list[str]:
        title = self._escape(item.get("title", "Untitled"))
        source_name = self._escape(item.get("source", "unknown"))
        lines = [f"{_BULLET} {title} [{source_name}]"]
        if item.get("published"):
            lines.append(f"  {self._human_time(item['published'])}")
        brief = self._item_brief(item)
        if brief:
            lines.append(f"  Brief: {self._escape(brief)}")
        article_page = item.get("article_page")
        if article_page:
            lines.append(f"  `_`[Read Full Article`{self._local_page_url(article_page)}]`_`")
        return lines

    def _is_emergency_page(self, page_name: str) -> bool:
        return page_name in {"disasters.mu", "emergencies.mu", "disasters.page", "emergencies.page"}

    def _render_emergency_page(
        self,
        page_name: str,
        source_snapshots: list[tuple[SourceDefinition, dict[str, Any] | None]],
    ) -> str:
        lines = [
            self._heading("Active Disaster & Incident Briefs"),
            self._divider(),
        ]
        all_items: list[dict[str, Any]] = []
        source_status: list[str] = []
        for source, snapshot in source_snapshots:
            if not snapshot:
                source_status.append(f"{_BULLET} {source.name}: awaiting first successful fetch")
                continue
            payload = snapshot.get("payload", {}) if isinstance(snapshot, dict) else {}
            updated = self._human_time(snapshot.get("fetched_at", payload.get("fetched_at", "unknown")))
            source_status.append(f"{_BULLET} {source.name}: {updated}")
            payload_items = payload.get("items", []) if isinstance(payload, dict) else []
            if not isinstance(payload_items, list):
                continue
            for item in payload_items:
                if not isinstance(item, dict):
                    continue
                merged = dict(item)
                merged.setdefault("source", source.name)
                all_items.append(merged)

        lines.append(f"Updated Sources: {len(source_snapshots)}")
        if source_status:
            lines.append("Source Status:")
            lines.extend(source_status[:10])
        lines.extend(["", "Priority Order: Critical Evacuations > Hurricane Watches > Fire Status", ""])

        if not all_items:
            lines.append("No active emergency incidents available.")
            lines.append("")
            lines.append("Generated by phantom-aggregator")
            return self._normalize(lines)

        sorted_items = sorted(all_items, key=self._emergency_sort_key, reverse=True)
        for item in sorted_items[:20]:
            severity = str(item.get("severity", "info")).upper()
            title = self._escape(item.get("title", "Untitled Incident"))
            lines.append(f"{_BULLET} [{severity}] {title}")
            lines.append(f"  Source: {self._escape(item.get('source', 'unknown'))}")
            published = item.get("published")
            if published:
                lines.append(f"  Updated: {self._human_time(published)}")
            details = self._item_brief(item)
            if details:
                lines.append(f"  Details: {self._escape(details)}")
            article_page = item.get("article_page")
            if article_page:
                lines.append(f"  `_`[Read Full Incident Brief`{self._local_page_url(article_page)}]`_`")
            lines.append("")

        lines.append("Generated by phantom-aggregator")
        return self._normalize(lines)

    def _emergency_sort_key(self, item: dict[str, Any]) -> tuple[int, datetime, str]:
        severity_map = {"critical": 6, "high": 5, "medium": 4, "info": 3}
        rank = int(item.get("severity_rank", severity_map.get(str(item.get("severity", "info")).lower(), 2)) or 2)
        event_type = str(item.get("event_type", "")).lower()
        if "evac" in event_type:
            rank += 3
        elif "hurricane" in event_type or "watch" in event_type:
            rank += 2
        elif "wildfire" in event_type or "fire" in event_type:
            rank += 1
        published = self._parse_timestamp(item.get("published"))
        return (rank, published, str(item.get("title", "")))

    def _parse_timestamp(self, value: Any) -> datetime:
        if not value:
            return datetime(1970, 1, 1, tzinfo=UTC)
        try:
            parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
            return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)
        except ValueError:
            return datetime(1970, 1, 1, tzinfo=UTC)

    def _human_time(self, value: Any) -> str:
        """Render a timestamp (ISO-8601 or RFC-2822) as a short, readable UTC string."""
        if not value or str(value).lower() == "unknown":
            return "unknown"
        text = str(value)
        parsed: datetime | None = None
        try:
            parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
        except ValueError:
            try:
                parsed = email.utils.parsedate_to_datetime(text)
            except (TypeError, ValueError):
                parsed = None
        if parsed is None:
            return text
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=UTC)
        return parsed.astimezone(UTC).strftime("%Y-%m-%d %H:%M UTC")

    def _domain(self, url: str) -> str:
        try:
            host = urlparse(str(url)).netloc
        except ValueError:
            host = ""
        return host.removeprefix("www.") or str(url)

    def _escape(self, text: Any) -> str:
        """Escape backticks in untrusted content so it can't hijack Micron formatting state."""
        return str(text).replace("\\", "\\\\").replace("`", "\\`")

    def _heading(self, text: str) -> str:
        return f">{text}"

    def _subheading(self, text: str) -> str:
        return f">>{text}"

    def _divider(self) -> str:
        return "-"

    def _normalize(self, lines: list[str]) -> str:
        max_width = min(max(settings.nomadnet_line_limit, 72), 80)
        normalized: list[str] = []
        for line in lines:
            if not line:
                normalized.append("")
                continue
            if self._is_micron_link(line) or self._is_micron_markup(line):
                normalized.append(line)
                continue
            if line.startswith(f"{_BULLET} "):
                indent = " " * (len(_BULLET) + 1)
            else:
                indent = " " * (len(line) - len(line.lstrip(" ")))
            wrapped = textwrap.wrap(
                line.strip(),
                width=max_width,
                initial_indent="" if line.startswith(f"{_BULLET} ") else indent,
                subsequent_indent=indent,
                break_long_words=False,
                break_on_hyphens=False,
            )
            normalized.extend(wrapped or [""])
        return "\n".join(normalized[: settings.nomadnet_max_lines]).strip() + "\n"

    def _item_brief(self, item: dict[str, Any]) -> str:
        brief = " ".join(str(item.get("body", "")).split())
        if not brief:
            return ""
        if len(brief) <= 220:
            return brief
        return brief[:217].rstrip() + "..."

    def _local_page_url(self, page_name: str) -> str:
        return f":/page/phantom-aggregator/{str(page_name).lstrip('/')}"

    def _is_micron_link(self, line: str) -> bool:
        stripped = line.strip()
        return stripped.startswith("`_`[") and stripped.endswith("]`_`")

    def _is_micron_markup(self, line: str) -> bool:
        stripped = line.strip()
        return stripped.startswith(">") or stripped == "-"
