from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from app.config import settings
from app.source_config import SourceDefinition, page_title


class NomadNetRenderer:
    """Renders normalized feed payloads into lightweight NomadNet-friendly text."""

    def __init__(self, output_dir: Path | None = None) -> None:
        self.output_dir = output_dir or settings.nomadnet_dir

    def render_space_weather(self, payload: dict[str, Any], summary: str) -> str:
        normalized = payload.get("normalized", {}) if isinstance(payload, dict) else {}
        lines = [
            "== SPACE WEATHER BRIEF ==",
            "----------------------------------------",
            f"Updated: {normalized.get('updated', payload.get('fetched_at', 'unknown'))}",
            f"SFI: {normalized.get('sfi', 0)}",
            f"Planetary K-Index: {normalized.get('k_index', 0)}",
            f"Geomagnetic Storm Risk: {normalized.get('geomagnetic_storm', 'UNKNOWN')}",
            "",
            "Summary:",
            summary,
            "",
            "Source: NOAA SWPC",
        ]
        return self._normalize(lines)

    def render_cyber_kev(self, payload: dict[str, Any], summary: str) -> str:
        rows = payload.get("latest_five", []) if isinstance(payload, dict) else []
        lines = [
            "== CYBER THREAT BRIEF ==",
            "----------------------------------------",
            f"Catalog Size: {payload.get('count_total', 0)}",
            f"Updated: {payload.get('fetched_at', 'unknown')}",
            "",
            "Latest Known Exploited Vulnerabilities:",
        ]
        if not rows:
            lines.append("- No recent KEV entries available.")
        for entry in rows[:5]:
            lines.append(
                f"- {entry.get('cveID', 'n/a')} | {entry.get('vendorProject', 'n/a')} | "
                f"{entry.get('vulnerabilityName', 'n/a')} ({entry.get('dateAdded', 'n/a')})"
            )

        lines.extend(["", "Summary:", summary, "", "Source: CISA KEV"])
        return self._normalize(lines)

    def render_news(self, payload: dict[str, Any], summary: str) -> str:
        items = payload.get("items", []) if isinstance(payload, dict) else []
        lines = [
            "== NEWS BRIEF ==",
            "----------------------------------------",
            f"Updated: {payload.get('fetched_at', 'unknown')}",
            f"Feed Count: {payload.get('source_count', 0)}",
            "",
            "Top Headlines:",
        ]
        if not items:
            lines.append("- No news items available.")
        for item in items[:10]:
            lines.append(f"- {item.get('title', 'Untitled')} [{item.get('source', 'unknown')}]")
            if item.get("published"):
                lines.append(f"  {item['published']}")

        lines.extend(["", "Summary:", summary])
        return self._normalize(lines)

    def render_weather(self, payload: dict[str, Any], summary: str) -> str:
        items = payload.get("items", []) if isinstance(payload, dict) else []
        weather_items = [
            item
            for item in items
            if any(
                keyword in f"{item.get('title', '')} {item.get('body', '')}".lower()
                for keyword in ("weather", "storm", "alert", "flood", "hurricane", "tornado")
            )
        ]
        lines = [
            "== WEATHER ALERT BRIEF ==",
            "----------------------------------------",
            f"Updated: {payload.get('fetched_at', 'unknown')}",
            "",
            "Recent Weather/Alert Headlines:",
        ]
        if not weather_items:
            lines.append("- No weather-related alerts detected in configured feeds.")
        for item in weather_items[:10]:
            lines.append(f"- {item.get('title', 'Untitled')} [{item.get('source', 'unknown')}]")
            if item.get("published"):
                lines.append(f"  {item['published']}")
        lines.extend(["", "Summary:", summary])
        return self._normalize(lines)

    def render_index(self, pages: list[tuple[str, str]] | None = None) -> str:
        links = pages or [
            ("weather.page", "Weather Alerts Brief"),
            ("space.page", "Space Weather Brief"),
            ("cyber.page", "Cyber Threat Brief"),
            ("news.page", "News Brief"),
        ]
        lines = [
            "== PHANTOM AGGREGATOR INDEX ==",
            "----------------------------------------",
        ]
        for page_name, title in links:
            lines.append(f"=> {page_name} {title}")
        lines.extend(["", "Generated by phantom-aggregator"])
        return self._normalize(lines)

    def write_page(self, page_name: str, content: str) -> Path:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / page_name
        path.write_text(content, encoding="utf-8")
        return path

    def write_index(self) -> Path:
        return self.write_page("index.mu", self.render_index())

    def write_dynamic_index(self, sources: list[SourceDefinition]) -> Path:
        pages: list[tuple[str, str]] = []
        seen: set[str] = set()
        grouped: dict[str, list[SourceDefinition]] = {}
        for source in sources:
            grouped.setdefault(source.nomadnet_page, []).append(source)
        for page_name in sorted(grouped):
            if page_name in seen:
                continue
            seen.add(page_name)
            pages.append((page_name, page_title(page_name, grouped[page_name])))
        return self.write_page("index.mu", self.render_index(pages))

    def render_dynamic_page(
        self,
        page_name: str,
        source_snapshots: list[tuple[SourceDefinition, dict[str, Any] | None]],
    ) -> str:
        defined_sources = [source for source, _ in source_snapshots]
        lines = [
            f"== {page_title(page_name, defined_sources).upper()} ==",
            "----------------------------------------",
            "",
        ]
        if not source_snapshots:
            lines.extend(["No configured sources for this page.", "", "Generated by phantom-aggregator"])
            return self._normalize(lines)

        for index, (source, snapshot) in enumerate(source_snapshots):
            lines.extend(self._render_source_section(source, snapshot))
            if index < len(source_snapshots) - 1:
                lines.extend(["", "----------------------------------------", ""])
        return self._normalize(lines)

    def _render_source_section(self, source: SourceDefinition, snapshot: dict[str, Any] | None) -> list[str]:
        lines = [
            f"[{source.name}]",
            f"Type: {source.type} | Category: {source.category}",
            f"URL: {source.url}",
        ]
        if not snapshot:
            lines.append("Status: awaiting first successful fetch")
            return lines

        payload = snapshot.get("payload", {}) if isinstance(snapshot, dict) else {}
        summary = snapshot.get("summary", "No summary available.") if isinstance(snapshot, dict) else "No summary available."
        lines.append(f"Updated: {snapshot.get('fetched_at', payload.get('fetched_at', 'unknown'))}")

        parser = source.options.get("parser")
        if parser == "space_weather_swpc":
            normalized = payload.get("normalized", {}) if isinstance(payload, dict) else {}
            lines.extend(
                [
                    f"SFI: {normalized.get('sfi', 0)}",
                    f"Planetary K-Index: {normalized.get('k_index', 0)}",
                    f"Geomagnetic Storm Risk: {normalized.get('geomagnetic_storm', 'UNKNOWN')}",
                ]
            )
        elif parser == "cisa_kev":
            lines.append(f"Catalog Size: {payload.get('count_total', 0)}")
            lines.append("Latest Entries:")
            for entry in payload.get("latest_five", [])[:5]:
                lines.append(
                    f"- {entry.get('cveID', 'n/a')} | {entry.get('vendorProject', 'n/a')} | "
                    f"{entry.get('vulnerabilityName', 'n/a')} ({entry.get('dateAdded', 'n/a')})"
                )
        elif source.type in {"rss", "atom"}:
            items = payload.get("items", []) if isinstance(payload, dict) else []
            lines.append(f"Items Available: {len(items)}")
            lines.append("Headlines:")
            for item in items[:5]:
                lines.append(f"- {item.get('title', 'Untitled')}")
                if item.get("published"):
                    lines.append(f"  {item['published']}")
        elif source.type == "text_feed":
            lines.append(f"Line Count: {payload.get('line_count', 0)}")
            lines.append("Preview:")
            for line in payload.get("lines", [])[:5]:
                lines.append(f"- {line}")
        else:
            preview = payload.get("preview", {}) if isinstance(payload, dict) else {}
            lines.append("Preview:")
            if isinstance(preview, dict):
                for key, value in list(preview.items())[:5]:
                    lines.append(f"- {key}: {value}")
            else:
                lines.append(f"- {preview}")

        lines.extend(["", "Summary:", summary])
        return lines

    def _normalize(self, lines: list[str]) -> str:
        max_width = min(max(settings.nomadnet_line_limit, 72), 80)
        normalized: list[str] = []
        for line in lines:
            if not line:
                normalized.append("")
                continue
            wrapped = textwrap.wrap(
                line,
                width=max_width,
                break_long_words=False,
                break_on_hyphens=False,
                replace_whitespace=False,
            )
            normalized.extend(wrapped or [""])
        return "\n".join(normalized[: settings.nomadnet_max_lines]).strip() + "\n"
